### ISSUE TITLE
External Dependency Eigen not available on bitbucket anymore

### ISSUE THREAD

**Issue by bmargula** [ZJCRT/mvs-texturing#8]
mvs-texturing/elibs/CMakeLists.txt line 25 contains a reference to Eigen 3.3.2 on bitbucket. However this is not available anymore and breaks our CI/CD chain.
Please update to use the new location https://gitlab.com/libeigen/eigen/-/archive/3.3.2/eigen-3.3.2.tar.gz 

Reference: eigen.tuxfamily.org

> https://bitbucket.org/eigen/eigen will be unavailable and replaced by an empty project pointing to https://gitlab.com/libeigen/eigen

**Comment by ZJCRT** [comment]
Merci Bruno. Ist gefixt.
